name: Close Unauthorized Issues
on:
  issues:
    types: [opened]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue author
        uses: actions/github-script@v6
        with:
          script: |
            const allowedUsers = ["Linwaru",];
            const author = context.payload.issue.user.login;
            if (!allowedUsers.includes(author)) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: "⛔ Esta issue foi fechada automaticamente pois você não tem permissão."
              });
              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                state: "closed"
              });
            }
